menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'fun', url: '/fun'}

social:
- {icon: 'github', link: 'https://github.com/chotong'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Zhaotong-Jia'}
